// Code generated by controller-gen. DO NOT EDIT.
// Run `make generate` to regenerate.
// Stub: replaces generated DeepCopy until controller-gen is first run.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of FooCRSpec into another FooCRSpec instance.
func (in *FooCRSpec) DeepCopyInto(out *FooCRSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of FooCRSpec.
func (in *FooCRSpec) DeepCopy() *FooCRSpec {
	if in == nil {
		return nil
	}
	out := new(FooCRSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of FooCRStatus into another FooCRStatus instance.
func (in *FooCRStatus) DeepCopyInto(out *FooCRStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of FooCRStatus.
func (in *FooCRStatus) DeepCopy() *FooCRStatus {
	if in == nil {
		return nil
	}
	out := new(FooCRStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of FooCR into another FooCR instance.
func (in *FooCR) DeepCopyInto(out *FooCR) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of FooCR.
func (in *FooCR) DeepCopy() *FooCR {
	if in == nil {
		return nil
	}
	out := new(FooCR)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *FooCR) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of FooCRList into another FooCRList instance.
func (in *FooCRList) DeepCopyInto(out *FooCRList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FooCR, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of FooCRList.
func (in *FooCRList) DeepCopy() *FooCRList {
	if in == nil {
		return nil
	}
	out := new(FooCRList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *FooCRList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
